imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            false
    csrf_protection: false
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:    false
    fragments:       false
    http_method_override: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

fos_rest:
    view:
        default_engine: json
        view_response_listener: force
        formats:
            jsonp: false
            json: true
            xml: false
            rss: false
        templating_formats:
            html: false
        mime_types:
            json: ['application/json', 'application/json;v=1.0']
            jpg: 'image/jpeg'
            html: 'image/png'
    body_listener: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    access_denied_listener: false
    format_listener:
#        media_type:
#            version_regex:        '/(v|version)=(?P<version>[0-9\.]+)/'
        rules:
            - { path: ^/, priorities: [ json ], fallback_format: ~, prefer_extension: true }
    routing_loader:
        default_format: json
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    body_converter:
        enabled: true
        validate: true

nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'LINK', 'UNLINK']
        allow_headers: ['content-type', 'authorization']
#        expose_headers: []
        max_age: 86400
#        hosts: []
#        origin_regex: false
    paths:
        '^/': ~



oneup_flysystem:
    adapters:
        cold_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads

    filesystems:
        cold_fs:
            adapter:    cold_adapter
            mount:      cold
            alias:      cold_fs

vich_uploader:
    db_driver: orm
    storage:   flysystem
    mappings:
        user_videos:
            uri_prefix:         /user_videos
            upload_destination: cold
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true